apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "some-docs-site-huh"
  description: "a docs site"
  annotations:
    github.com/project-slug: "hooloovooo/some-docs-site"
    backstage.io/rocdocs-ref: github:https://github.com/hooloovooo/some-docs-site/blob/docs/rocdocs.yaml
spec:
  type: documentation
  lifecycle: experimental
  owner: "guest"
